export interface EpisodeItem {
  id: string
  episodeNumber: number
  title: string
  duration: string
  size: string
  quality: string
  codec: string
  progress?: number // 0 to 1
  videoUrl?: string
  filePath?: string
}

export interface SeriesMetadata {
  showTitle: string
  seasonNumber: number
  totalEpisodes: number
  episodes: EpisodeItem[]
  currentEpisodeId?: string
}

export interface MediaItem {
  id: string
  title: string
  category: 'anime' | 'stream' | '4k' | 'audio'
  source: string
  quality: string
  codec: string
  duration: string
  size: string
  sizeBytes?: number
  timestamp: string
  audioTracks: string[]
  gradient: string
  bitrate: string
  videoUrl?: string
  posterUrl?: string
  series?: SeriesMetadata
}

export const INITIAL_MEDIA_ITEMS: MediaItem[] = [
  {
    id: 'media-1',
    title: "Frieren: Beyond Journey's End",
    category: 'anime',
    source: 'Crunchyroll',
    quality: '1080p 60fps',
    codec: 'HEVC',
    duration: '9h 42m',
    size: '43.6 GB',
    timestamp: '2h ago',
    audioTracks: ['Japanese (5.1)', 'English (Stereo)'],
    gradient: 'linear-gradient(145deg, rgba(99, 102, 241, 0.18) 0%, rgba(30, 27, 75, 0.38) 100%)',
    posterUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?q=80&w=800&auto=format&fit=crop',
    bitrate: '10.8 Mbps',
    series: {
      showTitle: "Frieren: Beyond Journey's End",
      seasonNumber: 1,
      totalEpisodes: 28,
      currentEpisodeId: 'ep-5',
      episodes: [
        {
          id: 'ep-1',
          episodeNumber: 1,
          title: "Ep 01: The Journey's End",
          duration: '24:18',
          size: '1.56 GB',
          quality: '1080p 60fps',
          codec: 'HEVC',
          progress: 1.0,
          filePath: 'C:\\Media\\Anime\\Frieren\\S01\\Frieren.S01E01.1080p.mkv',
        },
        {
          id: 'ep-2',
          episodeNumber: 2,
          title: "Ep 02: It Didn't Have to Be Magic...",
          duration: '24:02',
          size: '1.52 GB',
          quality: '1080p 60fps',
          codec: 'HEVC',
          progress: 1.0,
          filePath: 'C:\\Media\\Anime\\Frieren\\S01\\Frieren.S01E02.1080p.mkv',
        },
        {
          id: 'ep-3',
          episodeNumber: 3,
          title: 'Ep 03: Killing Magic',
          duration: '24:10',
          size: '1.55 GB',
          quality: '1080p 60fps',
          codec: 'HEVC',
          progress: 1.0,
          filePath: 'C:\\Media\\Anime\\Frieren\\S01\\Frieren.S01E03.1080p.mkv',
        },
        {
          id: 'ep-4',
          episodeNumber: 4,
          title: 'Ep 04: The Land Where Souls Rest',
          duration: '24:15',
          size: '1.54 GB',
          quality: '1080p 60fps',
          codec: 'HEVC',
          progress: 1.0,
          filePath: 'C:\\Media\\Anime\\Frieren\\S01\\Frieren.S01E04.1080p.mkv',
        },
        {
          id: 'ep-5',
          episodeNumber: 5,
          title: 'Ep 05: Phantoms of the Dead',
          duration: '24:22',
          size: '1.58 GB',
          quality: '1080p 60fps',
          codec: 'HEVC',
          progress: 0.35,
          filePath: 'C:\\Media\\Anime\\Frieren\\S01\\Frieren.S01E05.1080p.mkv',
        },
        {
          id: 'ep-6',
          episodeNumber: 6,
          title: 'Ep 06: The Hero of the Village',
          duration: '24:08',
          size: '1.53 GB',
          quality: '1080p 60fps',
          codec: 'HEVC',
          progress: 0,
          filePath: 'C:\\Media\\Anime\\Frieren\\S01\\Frieren.S01E06.1080p.mkv',
        },
        {
          id: 'ep-7',
          episodeNumber: 7,
          title: 'Ep 07: Like a Fairy Tale',
          duration: '24:12',
          size: '1.55 GB',
          quality: '1080p 60fps',
          codec: 'HEVC',
          progress: 0,
          filePath: 'C:\\Media\\Anime\\Frieren\\S01\\Frieren.S01E07.1080p.mkv',
        },
        {
          id: 'ep-8',
          episodeNumber: 8,
          title: 'Ep 08: Frieren the Slayer',
          duration: '24:25',
          size: '1.60 GB',
          quality: '1080p 60fps',
          codec: 'HEVC',
          progress: 0,
          filePath: 'C:\\Media\\Anime\\Frieren\\S01\\Frieren.S01E08.1080p.mkv',
        },
        {
          id: 'ep-9',
          episodeNumber: 9,
          title: 'Ep 09: Aura the Guillotine',
          duration: '24:30',
          size: '1.62 GB',
          quality: '1080p 60fps',
          codec: 'HEVC',
          progress: 0,
          filePath: 'C:\\Media\\Anime\\Frieren\\S01\\Frieren.S01E09.1080p.mkv',
        },
        {
          id: 'ep-10',
          episodeNumber: 10,
          title: 'Ep 10: A Powerful Mage',
          duration: '24:16',
          size: '1.56 GB',
          quality: '1080p 60fps',
          codec: 'HEVC',
          progress: 0,
          filePath: 'C:\\Media\\Anime\\Frieren\\S01\\Frieren.S01E10.1080p.mkv',
        },
        {
          id: 'ep-11',
          episodeNumber: 11,
          title: 'Ep 11: Winter in the Northern Lands',
          duration: '24:05',
          size: '1.51 GB',
          quality: '1080p 60fps',
          codec: 'HEVC',
          progress: 0,
          filePath: 'C:\\Media\\Anime\\Frieren\\S01\\Frieren.S01E11.1080p.mkv',
        },
        {
          id: 'ep-12',
          episodeNumber: 12,
          title: 'Ep 12: A Real Hero',
          duration: '24:18',
          size: '1.57 GB',
          quality: '1080p 60fps',
          codec: 'HEVC',
          progress: 0,
          filePath: 'C:\\Media\\Anime\\Frieren\\S01\\Frieren.S01E12.1080p.mkv',
        },
        {
          id: 'ep-13',
          episodeNumber: 13,
          title: "Ep 13: Aversion to One's Own Kind",
          duration: '24:14',
          size: '1.53 GB',
          quality: '1080p 60fps',
          codec: 'HEVC',
          progress: 0,
          filePath: 'C:\\Media\\Anime\\Frieren\\S01\\Frieren.S01E13.1080p.mkv',
        },
        {
          id: 'ep-14',
          episodeNumber: 14,
          title: 'Ep 14: Privilege of the Young',
          duration: '24:20',
          size: '1.58 GB',
          quality: '1080p 60fps',
          codec: 'HEVC',
          progress: 0,
          filePath: 'C:\\Media\\Anime\\Frieren\\S01\\Frieren.S01E14.1080p.mkv',
        },
        {
          id: 'ep-15',
          episodeNumber: 15,
          title: 'Ep 15: Smells of Trouble',
          duration: '24:11',
          size: '1.52 GB',
          quality: '1080p 60fps',
          codec: 'HEVC',
          progress: 0,
          filePath: 'C:\\Media\\Anime\\Frieren\\S01\\Frieren.S01E15.1080p.mkv',
        },
        {
          id: 'ep-16',
          episodeNumber: 16,
          title: 'Ep 16: Long-Lived Friends',
          duration: '24:09',
          size: '1.54 GB',
          quality: '1080p 60fps',
          codec: 'HEVC',
          progress: 0,
          filePath: 'C:\\Media\\Anime\\Frieren\\S01\\Frieren.S01E16.1080p.mkv',
        },
        {
          id: 'ep-17',
          episodeNumber: 17,
          title: 'Ep 17: Take Care',
          duration: '24:15',
          size: '1.55 GB',
          quality: '1080p 60fps',
          codec: 'HEVC',
          progress: 0,
          filePath: 'C:\\Media\\Anime\\Frieren\\S01\\Frieren.S01E17.1080p.mkv',
        },
        {
          id: 'ep-18',
          episodeNumber: 18,
          title: 'Ep 18: First-Class Mage Exam',
          duration: '24:28',
          size: '1.61 GB',
          quality: '1080p 60fps',
          codec: 'HEVC',
          progress: 0,
          filePath: 'C:\\Media\\Anime\\Frieren\\S01\\Frieren.S01E18.1080p.mkv',
        },
        {
          id: 'ep-19',
          episodeNumber: 19,
          title: 'Ep 19: Well-Laid Plans',
          duration: '24:12',
          size: '1.56 GB',
          quality: '1080p 60fps',
          codec: 'HEVC',
          progress: 0,
          filePath: 'C:\\Media\\Anime\\Frieren\\S01\\Frieren.S01E19.1080p.mkv',
        },
        {
          id: 'ep-20',
          episodeNumber: 20,
          title: 'Ep 20: Necessary Killing',
          duration: '24:24',
          size: '1.59 GB',
          quality: '1080p 60fps',
          codec: 'HEVC',
          progress: 0,
          filePath: 'C:\\Media\\Anime\\Frieren\\S01\\Frieren.S01E20.1080p.mkv',
        },
        {
          id: 'ep-21',
          episodeNumber: 21,
          title: 'Ep 21: The World of Magic',
          duration: '24:18',
          size: '1.57 GB',
          quality: '1080p 60fps',
          codec: 'HEVC',
          progress: 0,
          filePath: 'C:\\Media\\Anime\\Frieren\\S01\\Frieren.S01E21.1080p.mkv',
        },
        {
          id: 'ep-22',
          episodeNumber: 22,
          title: 'Ep 22: Future Enemies',
          duration: '24:06',
          size: '1.53 GB',
          quality: '1080p 60fps',
          codec: 'HEVC',
          progress: 0,
          filePath: 'C:\\Media\\Anime\\Frieren\\S01\\Frieren.S01E22.1080p.mkv',
        },
        {
          id: 'ep-23',
          episodeNumber: 23,
          title: 'Ep 23: Conquering the Labyrinth',
          duration: '24:26',
          size: '1.60 GB',
          quality: '1080p 60fps',
          codec: 'HEVC',
          progress: 0,
          filePath: 'C:\\Media\\Anime\\Frieren\\S01\\Frieren.S01E23.1080p.mkv',
        },
        {
          id: 'ep-24',
          episodeNumber: 24,
          title: 'Ep 24: Perfect Replicas',
          duration: '24:32',
          size: '1.63 GB',
          quality: '1080p 60fps',
          codec: 'HEVC',
          progress: 0,
          filePath: 'C:\\Media\\Anime\\Frieren\\S01\\Frieren.S01E24.1080p.mkv',
        },
        {
          id: 'ep-25',
          episodeNumber: 25,
          title: 'Ep 25: A Fatal Vulnerability',
          duration: '24:14',
          size: '1.55 GB',
          quality: '1080p 60fps',
          codec: 'HEVC',
          progress: 0,
          filePath: 'C:\\Media\\Anime\\Frieren\\S01\\Frieren.S01E25.1080p.mkv',
        },
        {
          id: 'ep-26',
          episodeNumber: 26,
          title: 'Ep 26: The Height of Magic',
          duration: '24:29',
          size: '1.62 GB',
          quality: '1080p 60fps',
          codec: 'HEVC',
          progress: 0,
          filePath: 'C:\\Media\\Anime\\Frieren\\S01\\Frieren.S01E26.1080p.mkv',
        },
        {
          id: 'ep-27',
          episodeNumber: 27,
          title: 'Ep 27: An Era of Humans',
          duration: '24:17',
          size: '1.56 GB',
          quality: '1080p 60fps',
          codec: 'HEVC',
          progress: 0,
          filePath: 'C:\\Media\\Anime\\Frieren\\S01\\Frieren.S01E27.1080p.mkv',
        },
        {
          id: 'ep-28',
          episodeNumber: 28,
          title: 'Ep 28: It Would Be Embarrassing When We Met Again',
          duration: '24:18',
          size: '1.58 GB',
          quality: '1080p 60fps',
          codec: 'HEVC',
          progress: 0,
          filePath: 'C:\\Media\\Anime\\Frieren\\S01\\Frieren.S01E28.1080p.mkv',
        },
      ],
    },
  },
  {
    id: 'media-2',
    title: 'Jujutsu Kaisen · Shibuya Incident',
    category: 'anime',
    source: 'Crunchyroll',
    quality: '1080p',
    codec: 'HEVC',
    duration: '8h 50m',
    size: '34.5 GB',
    timestamp: '5h ago',
    audioTracks: ['Japanese (5.1)', 'English (Stereo)'],
    gradient: 'linear-gradient(145deg, rgba(56, 189, 248, 0.16) 0%, rgba(15, 23, 42, 0.38) 100%)',
    posterUrl: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?q=80&w=800&auto=format&fit=crop',
    bitrate: '8.6 Mbps',
    series: {
      showTitle: 'Jujutsu Kaisen',
      seasonNumber: 2,
      totalEpisodes: 23,
      currentEpisodeId: 'jkk-1',
      episodes: [
        {
          id: 'jkk-1',
          episodeNumber: 1,
          title: 'Ep 01: Hidden Inventory',
          duration: '23:40',
          size: '1.50 GB',
          quality: '1080p',
          codec: 'HEVC',
          progress: 0,
          filePath: 'C:\\Media\\Anime\\Jujutsu Kaisen\\S02\\JJK.S02E01.1080p.mkv',
        },
        {
          id: 'jkk-2',
          episodeNumber: 2,
          title: 'Ep 02: Hidden Inventory, Part 2',
          duration: '23:35',
          size: '1.48 GB',
          quality: '1080p',
          codec: 'HEVC',
          progress: 0,
          filePath: 'C:\\Media\\Anime\\Jujutsu Kaisen\\S02\\JJK.S02E02.1080p.mkv',
        },
        {
          id: 'jkk-3',
          episodeNumber: 3,
          title: 'Ep 03: Hidden Inventory, Part 3',
          duration: '23:42',
          size: '1.52 GB',
          quality: '1080p',
          codec: 'HEVC',
          progress: 0,
          filePath: 'C:\\Media\\Anime\\Jujutsu Kaisen\\S02\\JJK.S02E03.1080p.mkv',
        },
        {
          id: 'jkk-4',
          episodeNumber: 4,
          title: 'Ep 04: Hidden Inventory, Part 4',
          duration: '23:38',
          size: '1.49 GB',
          quality: '1080p',
          codec: 'HEVC',
          progress: 0,
          filePath: 'C:\\Media\\Anime\\Jujutsu Kaisen\\S02\\JJK.S02E04.1080p.mkv',
        },
        {
          id: 'jkk-5',
          episodeNumber: 5,
          title: 'Ep 05: Premature Death',
          duration: '23:45',
          size: '1.51 GB',
          quality: '1080p',
          codec: 'HEVC',
          progress: 0,
          filePath: 'C:\\Media\\Anime\\Jujutsu Kaisen\\S02\\JJK.S02E05.1080p.mkv',
        },
        {
          id: 'jkk-6',
          episodeNumber: 6,
          title: "Ep 06: It's Like That",
          duration: '23:25',
          size: '1.44 GB',
          quality: '1080p',
          codec: 'HEVC',
          progress: 0,
          filePath: 'C:\\Media\\Anime\\Jujutsu Kaisen\\S02\\JJK.S02E06.1080p.mkv',
        },
        {
          id: 'jkk-7',
          episodeNumber: 7,
          title: 'Ep 07: Evening Festival',
          duration: '23:32',
          size: '1.47 GB',
          quality: '1080p',
          codec: 'HEVC',
          progress: 0,
          filePath: 'C:\\Media\\Anime\\Jujutsu Kaisen\\S02\\JJK.S02E07.1080p.mkv',
        },
        {
          id: 'jkk-8',
          episodeNumber: 8,
          title: 'Ep 08: The Shibuya Incident',
          duration: '23:48',
          size: '1.54 GB',
          quality: '1080p',
          codec: 'HEVC',
          progress: 0,
          filePath: 'C:\\Media\\Anime\\Jujutsu Kaisen\\S02\\JJK.S02E08.1080p.mkv',
        },
        {
          id: 'jkk-9',
          episodeNumber: 9,
          title: 'Ep 09: Shibuya Incident - Gate, Open',
          duration: '23:50',
          size: '1.55 GB',
          quality: '1080p',
          codec: 'HEVC',
          progress: 0,
          filePath: 'C:\\Media\\Anime\\Jujutsu Kaisen\\S02\\JJK.S02E09.1080p.mkv',
        },
        {
          id: 'jkk-10',
          episodeNumber: 10,
          title: 'Ep 10: Pandemonium',
          duration: '23:41',
          size: '1.50 GB',
          quality: '1080p',
          codec: 'HEVC',
          progress: 0,
          filePath: 'C:\\Media\\Anime\\Jujutsu Kaisen\\S02\\JJK.S02E10.1080p.mkv',
        },
        {
          id: 'jkk-11',
          episodeNumber: 11,
          title: 'Ep 11: Seance',
          duration: '23:36',
          size: '1.48 GB',
          quality: '1080p',
          codec: 'HEVC',
          progress: 0,
          filePath: 'C:\\Media\\Anime\\Jujutsu Kaisen\\S02\\JJK.S02E11.1080p.mkv',
        },
        {
          id: 'jkk-12',
          episodeNumber: 12,
          title: 'Ep 12: Dull Knife',
          duration: '23:39',
          size: '1.49 GB',
          quality: '1080p',
          codec: 'HEVC',
          progress: 0,
          filePath: 'C:\\Media\\Anime\\Jujutsu Kaisen\\S02\\JJK.S02E12.1080p.mkv',
        },
        {
          id: 'jkk-13',
          episodeNumber: 13,
          title: 'Ep 13: Red Scale',
          duration: '23:44',
          size: '1.51 GB',
          quality: '1080p',
          codec: 'HEVC',
          progress: 0,
          filePath: 'C:\\Media\\Anime\\Jujutsu Kaisen\\S02\\JJK.S02E13.1080p.mkv',
        },
        {
          id: 'jkk-14',
          episodeNumber: 14,
          title: 'Ep 14: Fluctuations',
          duration: '23:46',
          size: '1.53 GB',
          quality: '1080p',
          codec: 'HEVC',
          progress: 0,
          filePath: 'C:\\Media\\Anime\\Jujutsu Kaisen\\S02\\JJK.S02E14.1080p.mkv',
        },
        {
          id: 'jkk-15',
          episodeNumber: 15,
          title: 'Ep 15: Fluctuations, Part 2',
          duration: '23:42',
          size: '1.50 GB',
          quality: '1080p',
          codec: 'HEVC',
          progress: 0,
          filePath: 'C:\\Media\\Anime\\Jujutsu Kaisen\\S02\\JJK.S02E15.1080p.mkv',
        },
        {
          id: 'jkk-16',
          episodeNumber: 16,
          title: 'Ep 16: Thunderclap',
          duration: '23:55',
          size: '1.58 GB',
          quality: '1080p',
          codec: 'HEVC',
          progress: 0,
          filePath: 'C:\\Media\\Anime\\Jujutsu Kaisen\\S02\\JJK.S02E16.1080p.mkv',
        },
        {
          id: 'jkk-17',
          episodeNumber: 17,
          title: 'Ep 17: Thunderclap, Part 2',
          duration: '23:58',
          size: '1.60 GB',
          quality: '1080p',
          codec: 'HEVC',
          progress: 0,
          filePath: 'C:\\Media\\Anime\\Jujutsu Kaisen\\S02\\JJK.S02E17.1080p.mkv',
        },
        {
          id: 'jkk-18',
          episodeNumber: 18,
          title: 'Ep 18: Right and Wrong',
          duration: '23:40',
          size: '1.49 GB',
          quality: '1080p',
          codec: 'HEVC',
          progress: 0,
          filePath: 'C:\\Media\\Anime\\Jujutsu Kaisen\\S02\\JJK.S02E18.1080p.mkv',
        },
        {
          id: 'jkk-19',
          episodeNumber: 19,
          title: 'Ep 19: Right and Wrong, Part 2',
          duration: '23:43',
          size: '1.51 GB',
          quality: '1080p',
          codec: 'HEVC',
          progress: 0,
          filePath: 'C:\\Media\\Anime\\Jujutsu Kaisen\\S02\\JJK.S02E19.1080p.mkv',
        },
        {
          id: 'jkk-20',
          episodeNumber: 20,
          title: 'Ep 20: Right and Wrong, Part 3',
          duration: '23:47',
          size: '1.53 GB',
          quality: '1080p',
          codec: 'HEVC',
          progress: 0,
          filePath: 'C:\\Media\\Anime\\Jujutsu Kaisen\\S02\\JJK.S02E20.1080p.mkv',
        },
        {
          id: 'jkk-21',
          episodeNumber: 21,
          title: 'Ep 21: Metamorphosis',
          duration: '23:51',
          size: '1.56 GB',
          quality: '1080p',
          codec: 'HEVC',
          progress: 0,
          filePath: 'C:\\Media\\Anime\\Jujutsu Kaisen\\S02\\JJK.S02E21.1080p.mkv',
        },
        {
          id: 'jkk-22',
          episodeNumber: 22,
          title: 'Ep 22: Metamorphosis, Part 2',
          duration: '23:45',
          size: '1.52 GB',
          quality: '1080p',
          codec: 'HEVC',
          progress: 0,
          filePath: 'C:\\Media\\Anime\\Jujutsu Kaisen\\S02\\JJK.S02E22.1080p.mkv',
        },
        {
          id: 'jkk-23',
          episodeNumber: 23,
          title: 'Ep 23: Shibuya Incident - Gate, Close',
          duration: '23:49',
          size: '1.54 GB',
          quality: '1080p',
          codec: 'HEVC',
          progress: 0,
          filePath: 'C:\\Media\\Anime\\Jujutsu Kaisen\\S02\\JJK.S02E23.1080p.mkv',
        },
      ],
    },
  },
  {
    id: 'media-3',
    title: 'GDC 2026 Keynote: Next-Gen Shaders',
    category: '4k',
    source: 'YouTube 4K',
    quality: '4K HDR',
    codec: 'AV1',
    duration: '1h 14m',
    size: '5.80 GB',
    timestamp: 'Yesterday',
    audioTracks: ['English (5.1)'],
    gradient: 'linear-gradient(145deg, rgba(139, 92, 246, 0.18) 0%, rgba(30, 27, 75, 0.38) 100%)',
    posterUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=800&auto=format&fit=crop',
    bitrate: '28.4 Mbps',
  },
  {
    id: 'media-4',
    title: 'The Primeagen · Rust Ingestion Stream',
    category: 'stream',
    source: 'Twitch VOD',
    quality: '1440p',
    codec: 'AV1',
    duration: '3h 42m',
    size: '9.80 GB',
    timestamp: 'Yesterday',
    audioTracks: ['English (Stereo)'],
    gradient: 'linear-gradient(145deg, rgba(71, 85, 105, 0.22) 0%, rgba(15, 23, 42, 0.38) 100%)',
    posterUrl: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?q=80&w=800&auto=format&fit=crop',
    bitrate: '14.2 Mbps',
  },
  {
    id: 'media-5',
    title: 'Cyberpunk Edgerunners Soundtrack',
    category: 'audio',
    source: 'Tidal Master',
    quality: 'FLAC 24-bit',
    codec: 'Lossless',
    duration: '42:15',
    size: '420 MB',
    timestamp: '2 days ago',
    audioTracks: ['Stereo Master'],
    gradient: 'linear-gradient(145deg, rgba(168, 85, 247, 0.16) 0%, rgba(15, 23, 42, 0.38) 100%)',
    posterUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?q=80&w=800&auto=format&fit=crop',
    bitrate: '3,200 kbps',
  },
  {
    id: 'media-6',
    title: 'Blade Runner 2049: Color Grade Master',
    category: '4k',
    source: 'Vimeo 4K',
    quality: '4K HDR',
    codec: 'ProRes',
    duration: '38:50',
    size: '4.20 GB',
    timestamp: '3 days ago',
    audioTracks: ['Dolby Atmos'],
    gradient: 'linear-gradient(145deg, rgba(56, 189, 248, 0.18) 0%, rgba(30, 41, 59, 0.40) 100%)',
    posterUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=800&auto=format&fit=crop',
    bitrate: '32.0 Mbps',
  },
  {
    id: 'media-7',
    title: 'Chainsaw Man · Ep 12 Finale Master',
    category: 'anime',
    source: 'Direct HLS',
    quality: '1080p 60fps',
    codec: 'HEVC',
    duration: '24:02',
    size: '1.92 GB',
    timestamp: '4 days ago',
    audioTracks: ['Japanese (5.1)'],
    gradient: 'linear-gradient(145deg, rgba(99, 102, 241, 0.16) 0%, rgba(15, 23, 42, 0.38) 100%)',
    posterUrl: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?q=80&w=800&auto=format&fit=crop',
    bitrate: '11.4 Mbps',
  },
  {
    id: 'media-8',
    title: 'Apple Special Event: M5 Architecture',
    category: '4k',
    source: 'Apple Master',
    quality: '4K 60fps',
    codec: 'HEVC',
    duration: '1h 08m',
    size: '6.15 GB',
    timestamp: '5 days ago',
    audioTracks: ['Spatial Audio'],
    gradient: 'linear-gradient(145deg, rgba(100, 116, 139, 0.20) 0%, rgba(15, 23, 42, 0.38) 100%)',
    posterUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=800&auto=format&fit=crop',
    bitrate: '26.8 Mbps',
  },
  {
    id: 'media-9',
    title: 'Joe Hisaishi & Philharmonic Orchestra',
    category: 'audio',
    source: 'Studio Master',
    quality: 'FLAC 24-bit',
    codec: 'Lossless',
    duration: '1h 22m',
    size: '880 MB',
    timestamp: '6 days ago',
    audioTracks: ['Stereo Master'],
    gradient: 'linear-gradient(145deg, rgba(129, 140, 248, 0.16) 0%, rgba(15, 23, 42, 0.38) 100%)',
    posterUrl: 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?q=80&w=800&auto=format&fit=crop',
    bitrate: '4,608 kbps',
  },
  {
    id: 'media-10',
    title: 'Next.js 16 Compiler Architecture',
    category: 'stream',
    source: 'YouTube 4K',
    quality: '1440p',
    codec: 'VP9',
    duration: '2h 10m',
    size: '4.75 GB',
    timestamp: '1 week ago',
    audioTracks: ['English (Stereo)'],
    gradient: 'linear-gradient(145deg, rgba(71, 85, 105, 0.20) 0%, rgba(15, 23, 42, 0.38) 100%)',
    posterUrl: 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?q=80&w=800&auto=format&fit=crop',
    bitrate: '12.0 Mbps',
  },
]
